### ISSUE TITLE
Bot is not worked with new ids

### ISSUE THREAD

**Issue by PashaGeronimo** [karipov/creationDate#7]
for example 
/id 5291679714 - not worked because of the length of the number
/id 529167971 - worked

**Comment by m0rphed** [comment]
I have the same issue 😭
I think that the problem is in the user id threshold (`1_700_000_000` ) [here](https://github.com/karipov/creationDate/blob/ccf1eb6faecdf48d447293feab263a118c1edcc1/src/handlers/app.py#L76). If increasing this threshold would not affect the general work of, I believe it is pretty easy to fix. I'll try to figure it out if no one gets ahead of me and fixes it first

**Comment by karipov** [comment]
Sorry guys, I never expected the bot to get as popular as it is, so it's been kind of pushed to the back of my mind. I'm sending in an update server-side now.
